### ISSUE TITLE
Python error Rubrik special agent

### ISSUE THREAD

**Issue by Edmund-Blackadder** [iteratio-com/Exchange#8]
Tested with version 2.2.0p16 & extension version 0.9.3, on a completely fresh site hosted via a docker container.

We get the following error from the Check_MK service:

```
Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/SITE/lib/python3.11/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/SITE/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/SITE/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/SITE/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/SITE/local/share/check_mk/agents/special/agent_rubrik", line 164, in <module>
sys.exit(main(sys.argv[1:]))
^^^^^^^^^^^^^^^^^^
File "/omd/sites/SITE/local/share/check_mk/agents/special/agent_rubrik", line 148, in main
api.login()
File "/omd/sites/SITE/local/share/check_mk/agents/special/agent_rubrik", line 65, in login
self.token = response.json().get("token")
^^^^^^^^^^^^^^^
File "/omd/sites/SITE/lib/python3.11/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

https://exchange.checkmk.com/p/rubrik-agent

https://github.com/iteratio-com/Exchange/tree/main/Rubrik_special_agent

**Comment by kleinski** [comment]
@Edmund-Blackadder can you please insert into line 64 the following print?
`print(response.text)`
let that agent run and send the output back here?

**Comment by Edmund-Blackadder** [comment]
@kleinski Thanks for taking the time.

The output of the script shows getting a 404 response. I tried  API endpoint via CURL, and got the same result.

Our version of Rubrik does not have api/v1/service_account/session.

So it does not look like the script is at fault.

Can you tell me what version of Rubrik CDM you are using?

**Comment by kleinski** [comment]
@Edmund-Blackadder we tested the API successfully with Rubrik CDM-Version: 8.1.3-p2-24912.

**Comment by Edmund-Blackadder** [comment]
Thank you!
